<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title><?= htmlspecialchars("Tasks - FullStuck Showcase (" . "v0.2.0" . ")" ?? '', ENT_QUOTES, 'UTF-8') ?></title><link rel="stylesheet" href="/assets/style.css"><link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700&amp;display=swap" rel="stylesheet"></head><body>
<div class="app-container" id="app-content"><header><div class="logo-wrapper"><div class="logo-icon">&#128640;</div><h1>Tasks</h1></div><p>FullStuck.php Framework Showcase</p></header>
<?php if (fst_flash_has("msg")): ?><div class="alert alert-msg"><?= htmlspecialchars(fst_flash_get("msg") ?? '', ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?><?php if (fst_flash_has("error")): ?><div class="alert alert-error"><?= htmlspecialchars(fst_flash_get("error") ?? '', ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?>
<form class="form-add" action="/add" method="POST" enctype="multipart/form-data" data-fst-history="false"><input type="text" name="task" placeholder="What needs to be done?" required autocomplete="off"><input type="file" name="file" accept=".png,.jpg,.pdf,.txt"><button type="submit" class="btn-primary">Add</button><?= fst_csrf_field() ?? '' ?></form>
<ul class="todo-list"><?php if (empty($todos)): ?><li class="empty-state"><div class="empty-icon">&#128237;</div><p>Belum ada task. Tambahkan sekarang!</p></li><?php endif; ?>
<?php foreach ($todos as $todo): ?><li class="<?= htmlspecialchars($todo["is_done"] ? "todo-item done" : "todo-item" ?? '', ENT_QUOTES, 'UTF-8') ?>"><div class="task-content"><span class="task-text"><?= htmlspecialchars($todo["task"] ?? '', ENT_QUOTES, 'UTF-8') ?></span><?php if (!empty($todo["attachment"]) && !preg_match("/\.(png|jpg|jpeg|gif|webp)$/i", $todo["attachment"])): ?><a class="task-file" href="<?= htmlspecialchars("/" . $todo["attachment"] ?? '', ENT_QUOTES, 'UTF-8') ?>" target="_blank"><?= htmlspecialchars("📄 View " . strtoupper(pathinfo($todo["attachment"], PATHINFO_EXTENSION)) ?? '', ENT_QUOTES, 'UTF-8') ?></a><?php endif; ?><?php if (!empty($todo["attachment"]) && preg_match("/\.(png|jpg|jpeg|gif|webp)$/i", $todo["attachment"])): ?><img class="task-img" src="<?= htmlspecialchars("/" . $todo["attachment"] ?? '', ENT_QUOTES, 'UTF-8') ?>" alt="Attachment" style="max-height:80px;border-radius:8px;display:block;"><?php endif; ?></div>
<div class="task-actions"><form class="form-toggle" action="<?= htmlspecialchars("/toggle/" . $todo["id"] ?? '', ENT_QUOTES, 'UTF-8') ?>" method="POST" data-fst-history="false"><button type="submit" class="btn-success"><?= htmlspecialchars($todo["is_done"] ? "Undo" : "Done" ?? '', ENT_QUOTES, 'UTF-8') ?></button><?= fst_csrf_field() ?? '' ?></form><form class="form-delete" action="<?= htmlspecialchars("/delete/" . $todo["id"] ?? '', ENT_QUOTES, 'UTF-8') ?>" method="POST" data-fst-history="false"><button type="submit" class="btn-danger">Del</button><?= fst_csrf_field() ?? '' ?></form></div></li><?php endforeach; ?></ul></div>
</body></html>
